### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by aarshps** [im-aadhirapr/resume-screener#1]
- Change copy the code to clone the code in the installation instructions
- When I installed Python, my python3 commands are only working
- Same is the case for pip as well
- So I have this confusion, so I expect an explanation in the Installation readme
- All the required dependencies, libraries need to be there in a requirements.txt file
- Read about it and create it
- So when we do a pip install that requirements.txt, it should basically install all the dependencies

**Comment by im-aadhirapr** [comment]
- Changed copy the code to clone the code in readme.
   - For the verification of python installation, added an alternative code
   for it.
   - Before running pip comment check whether you have installed pip along
   with python. Reference link: https://youtu.be/dYfKJMPNMDw
   - If pip is already installed but not working then upgrade it with: py
   -m pip install --upgrade pip
   - Added all the libraries to be installed.
   - Updated the readme and added to github

Check installation update on GitHub
<https://github.com/im-aadhirapr/resume-screener/blob/main/installation.md>
Thank You

**Comment by aarshps** [comment]
The formatting is not correct!

<img width="740" alt="Screenshot 2023-05-21 at 6 34 27 PM" src="https://github.com/im-aadhirapr/resume-screener/assets/11371727/b01da503-b015-4196-86d8-3a099c78c7ad">

Also there is a method to put all dependencies in a requirements.txt file and then use that file to install.

That is now you have dependencies with different Python libraries. You can't expect users to pip install each libraries. Instead, they should pip install that requirements.txt file which contains all these dependencies and then it should all get installed automatically.

**Comment by aarshps** [comment]
@im-aadhirapr also when you write a readme file, it should be generic. Windows is not the only Operating System we have. So keep that in mind as well.

**Comment by im-aadhirapr** [comment]
- Added a requirement.txt file to install all the libraries at a stretch.

Check requirements.txt : resume-screener/requirements.txt at main ·
im-aadhirapr/resume-screener (github.com)
<https://github.com/im-aadhirapr/resume-screener/blob/main/requirements.txt>

**Comment by aarshps** [comment]
Package installations ran fine. But what is the next step? How to create a python environment? Steps are not clear.

Explain all the steps required.

<img width="811" alt="image" src="https://github.com/im-aadhirapr/resume-screener/assets/11371727/41015000-0e64-4123-8fa5-4e52dfec34fd">

**Comment by aarshps** [comment]
And also the whole intention of using Python environments in to install the libraries and dependencies within that environment. So your steps order should be first create venv, then install all libraries, then run the application.

**Comment by aarshps** [comment]
I have moved the requirements.txt file into the app folder. That is where it should be there. Closing this issue. Have opened 2 new issues. Please look at it and do the needful.

@im-aadhirapr
