### ISSUE TITLE
Project scope not clear

### ISSUE THREAD

**Issue by aarshps** [im-aadhirapr/resume-screener#5]
The scope of the project is not clear. Please add clear scope to the readme.

@im-aadhirapr

**Comment by im-aadhirapr** [comment]
I'll update you ASAP

**Comment by aarshps** [comment]
Why closed? @im-aadhirapr

**Comment by aarshps** [comment]
The scope is still not clear, why is the issue being closed? @im-aadhirapr

**Comment by im-aadhirapr** [comment]
I've already posted the project scope, check readme.

**Comment by aarshps** [comment]
@im-aadhirapr the scope is not clear. Anyone who comes to the repo should be able to just go through the scope and understand what the repo is all about. It should be detailed.

**Comment by aarshps** [comment]
@im-aadhirapr ?

**Comment by im-aadhirapr** [comment]
Updated
